### ISSUE TITLE
linuxmuster-prepare with from srcatch installation - bittorrent - config not changed, bttorrent does not start

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-prepare#14]
Having used the linuxmuster-prepare script with a from scratch installation, I notices that bittorrent does not start while rebooting the server.
I took a look at the configuration file
/etc/default/bittorrent
the option 
START_BTTRACK=0
was set. I changed the value to 1 and started bittorrent. It worked.

I think it should be set correctly during setup instead.

Thanks.

**Comment by HappyBasher** [comment]
Indeed this is done by linuxmuster-setup, see https://github.com/linuxmuster/linuxmuster-base7/blob/master/lib/setup.d/n_linbo.py.
