### ISSUE TITLE
lmn7-appliance script is broken due to changes in linuxmuster-prepair

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-prepare#19]
Hi Thomas,

in the lmn7-appliance script and in the Readme.md here
https://github.com/linuxmuster/linuxmuster-prepare/blob/master/README.md
the "new" switch for linuxmuster-prepair, which is invoked by lmn7-appliance, is missing.
It is the "-i" for "initial" which is necessary for prepairing the second Storage by the script.
I was wondering a while, why the script never touched my /dev/vdb for partitioning and initializing the lvm.
When i invoked linuxmuster-prepair directly it said: "-s" or "-i" was necessary.
Running prepair with -i partitioned my Storage correctly.
Now i'll try again witch -i 
Yours 
Holger

**Comment by baumhof** [comment]
Hi Thomas,

i just saw the "-i" is in the lmn7-appliance script included .. but did not work in my setup.
I will investigate more ..
yours
Holger

**Comment by HappyBasher** [comment]
Is this relevant yet?

**Comment by HappyBasher** [comment]
Closed due to inactivity.
