### ISSUE TITLE
Install 22.04

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-prepare#21]
Hello,

I open a new issue to collect some errors or warnings in the installation process under Jammy 22.04.

I encountered a little warning while removing the package `lxd-client` : https://github.com/linuxmuster/linuxmuster-prepare/blob/06fba32122586bb5ea11b8be58f34815869a167a/lmn71-appliance#L94
This package no longer exists under Jammy, it's actually only installed with `snap`.

Cheers

Arnaud

**Comment by FlorianKrammel** [comment]
Missing: "python3-reconfigure" in Ubuntu 22.04 and Debian 11.

Outdated: pip in Ubuntu 18.04 - needs manunal upgrade - "python3 -m pip install --upgrade pip"

**Comment by HappyBasher** [comment]
Fixed.
