### ISSUE TITLE
rsync: send_files failed to open "/var/lib/lxcfs/...": Permission denied (13)

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-prepare#22]
lmn71-prepare -i (-u) -l /dev/sdb -p server 

laufen in Fehler beim rsync bis zum Abruch. :-(

`### lmn71-prepare`
`## Profile`
`# Creating logical volume global.`
`  Logical volume "global" created.`
`mke2fs 1.44.1 (24-Mar-2018)`
`Discarding device blocks: done                            `   
`Creating filesystem with 2621440 4k blocks and 655360 inodes`
`Filesystem UUID: 07ab38df-ef7a-4d85-967c-07f1300ba85b`
`Superblock backups stored on blocks: `
`        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632`
` `
`Allocating group tables: done                            `   
`Writing inode tables: done                            `   
`Creating journal (16384 blocks): done`
`Writing superblocks and filesystem accounting information: done `
` `
`# Creating logical volume default-school.`
`  Logical volume "default-school" created.`
`mke2fs 1.44.1 (24-Mar-2018)`
`Discarding device blocks: done                            `   
`Creating filesystem with 10484736 4k blocks and 2621440 inodes`
`Filesystem UUID: f91dba18-3876-4458-a999-da24ab87a4c3`
`Superblock backups stored on blocks: `
`        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, `
`        4096000, 7962624`
` `
`Allocating group tables: done                            `   
`Writing inode tables: done                            `   
`Creating journal (65536 blocks): done`
`Writing superblocks and filesystem accounting information: done   `   
` `
`# Writing /etc/fstab.`
`# Moving /var.`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/accounts-daemon.service/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/apparmor.service/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/apport.service/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/atd.service/blkio.reset_stats": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/system.slice/blk-availability.service/blkio.reset_stats": Permission denied (13)`
` `
`...`
` `
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/memory/user.slice/memory.force_empty": Permission denied (13)`
`rsync: send_files failed to open "/var/lib/lxcfs/cgroup/memory/user.slice/memory.pressure_level": Permission denied (13)`
`rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]`
`root@server:~# lsblk`
`NAME                     MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT`
`sda                        8:0    0   25G  0 disk `
`├─sda1                     8:1    0    1M  0 part `
`└─sda2                     8:2    0   25G  0 part /`
`sdb                        8:16   0  100G  0 disk `
`├─vg_srv-var             253:0    0   10G  0 lvm  /mnt`
`├─vg_srv-linbo           253:1    0   40G  0 lvm  `
`├─vg_srv-global          253:2    0   10G  0 lvm  `
`└─vg_srv-default--school 253:3    0   40G  0 lvm  `
`sr0                       11:0    1  969M  0 rom `

**Comment by MachtDochNix** [comment]
Error can be avoided if lxcfs is deleted by apt purge before linuxmuster-prepare is called.
It would be better if the script does this automatically before copying var.
lxcfs was automatically installed during the installation of Ubuntu.

**Comment by HappyBasher** [comment]
Fixed with 626b0ee894a68b74ef31ff0cec85d3ec2ecb06a8 & 636666dff4faeec8c2202774ea8f66957bd87727.
