### ISSUE TITLE
ModuleMotFoundError while running lmn-appliance on fresh installed ubuntu 22.04.5

### ISSUE THREAD

**Issue by michaelkohls** [linuxmuster/linuxmuster-prepare#26]
While running lmn-appliance on a fresh installed Ubuntu 22.04.5 a error occurs. 
![grafik](https://github.com/user-attachments/assets/01e3755d-6ed9-4ab7-b73d-e9e67a85d87c)
After running ''pip3 install chardet'', the script works.

**Comment by HappyBasher** [comment]
Which package shows this error? I think this is not a fault of lmn-prepare but of the package to be installed.

**Comment by michaelkohls** [comment]
After I tried again today, the script runs fine. Don't know why... 
Sorry for confusion.
