### ISSUE TITLE
lmn-appliance script muss angepaßt werden

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-prepare#7]
Hallo Thomas,

ich habe Heute einen vanilla Install versucht.
Das lmn-appliance script bricht sehr schnell ab.
Das liegt zuerst mal dran, dass es die Datei archive.linuxmuster.net.gpg nciht findet.
Ich hab im Script *.key draus gemacht, dann läuft das script weiter, läd aber linuxmuster-prepair nicht herunter, weil der key nicht importiert wurde (was wohl mit dem gpg key nicht nötig ist), also hab ich den key geholt und selber integriert: dann lief das script durch.

LG

Holger

**Comment by HappyBasher** [comment]
Hallo Holger,

danke für den Hinweis. Da hat jemand den gpg-Key entfernt. :-(
Das sollte nicht sein.

VG, Thomas

Am 22.06.19 um 14:27 schrieb Holger Baumhof:

**Comment by baumhof** [comment]
Hallo Thomas,

das Problem besteht noch immer.
Der gpg Key liegt zwar im Verzeichnis neben dem "key", aber weder gpg noch "key" werden durch dein script importiert. Ich weiß nicht, wieso nicht.
Ich hab den key jetzt von Hand runtergeholt und dann mit apt-key add eingespielt: jetzt läuft das script.

LG

Holger

**Comment by emdete** [comment]
Im readme steht das korrekte `wget` mit `..../lmn7-appliance`, danach wird aber `lmn7-appliance.py` gestartet - ist das korrekt?

Und im Script würde ich oben besser `#!/usr/bin/env python3` nutzen.
