### ISSUE TITLE
HInweis zu Passwort in der OPNsense fehlt

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-prepare#8]
Hallo Thomas,

linuxmustrer-prepair setzt voraus, dass die OPNsense das rootPasswort Muster! hat.
Hat sie das nicht, so bricht linuxmuster-prepare immer ab mit "Download failed"
Das sollte auf jeden Fall ins linuxmuster-prepare- wiki.

LG

Holger

**Comment by HappyBasher** [comment]
lmn-prepare does not download anything from the firewall. Not relevant. Do you mean linuxmuster-setup?
